name:                advent
version:             0.1.0.0
github:              "b-mehta/advent"
license:             BSD3
author:              "Bhavik Mehta"
maintainer:          "bhavikmehta8@gmail.com"
copyright:           "2018 Bhavik Mehta"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- vector >= 0.12
- containers >= 0.5
- megaparsec >= 7.0.3
- multiset >= 0.3.4.1
- split >= 0.2.3.3
- mtl
- microlens-platform
- comonad

ghc-options:
  - -O2

default-extensions:
  - TupleSections

library:
  source-dirs:
    - common
  exposed-modules:
    - Common
    - Parsers

executables:
  day01:
    main: day01.hs
    source-dirs: sols
    dependencies: advent
  day02:
    main: day02.hs
    source-dirs: sols
    dependencies: advent
  day03:
    main: day03.hs
    source-dirs: sols
    dependencies: advent
  day04:
    main: day04.hs
    source-dirs: sols
    dependencies: advent
  day05:
    main: day05.hs
    source-dirs: sols
    dependencies: advent
  day06:
    main: day06.hs
    source-dirs: sols
    dependencies: advent
  day07:
    main: day07.hs
    source-dirs: sols
    dependencies: advent
  day08:
    main: day08.hs
    source-dirs: sols
    dependencies: advent
  day09:
    main: day09.hs
    source-dirs: sols
    dependencies: advent
  day10:
    main: day10.hs
    source-dirs: sols
    dependencies: advent
  day11:
    main: day11.hs
    source-dirs: sols
    dependencies: advent
  day12:
    main: day12.hs
    source-dirs: sols
    dependencies: advent
  day13:
    main: day13.hs
    source-dirs: sols
    dependencies: advent
